service: crudserverlessawsrds
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - ec2:CreateNetworkInterface
            - ec2:CreateSecurityGroup
            - ec2:DeleteNetworkInterface
            - ec2:DeleteSecurityGroup
            - ec2:DescribeAvailabilityZones
            - ec2:DescribeInternetGateways
            - ec2:DescribeSecurityGroups
            - ec2:DescribeSubnets
            - ec2:DescribeVpcAttribute
            - ec2:DescribeVpcs
            - ec2:ModifyNetworkInterfaceAttribute
            - ec2:ModifyVpcEndpoint
            - ec2:RevokeSecurityGroupIngress
            - ec2:CreateVpcEndpoint
            - ec2:DescribeVpcEndpoints
            - ec2:DeleteVpcEndpoints
            - ec2:AssignPrivateIpAddresses
            - ec2:UnassignPrivateIpAddresses
          Resource:
            - "*"
functions:
  GetFuncionarios:
    handler: handler.getFuncionarios
    events:
      - http:
          path: /
          method: get
          cors: true
    vpc:
      securityGroupIds:
        - sg-ff8bfadd
      subnetIds:
        - subnet-1a29e03b
        - subnet-c4a93b89
        - subnet-7de12e22
        - subnet-48eef876
        - subnet-1a880c14
        - subnet-cc76b5aa
  PostFuncionarios:
    handler: handler.postFuncionarios
    events:
      - http:
          path: /
          method: post
          cors: true
    vpc:
      securityGroupIds:
        - sg-ff8bfadd
      subnetIds:
        - subnet-1a29e03b
        - subnet-c4a93b89
        - subnet-7de12e22
        - subnet-48eef876
        - subnet-1a880c14
        - subnet-cc76b5aa
  PutFuncionarios:
    handler: handler.putFuncionarios
    events:
      - http:
          path: /
          method: put
          cors: true
    vpc:
      securityGroupIds:
        - sg-ff8bfadd
      subnetIds:
        - subnet-1a29e03b
        - subnet-c4a93b89
        - subnet-7de12e22
        - subnet-48eef876
        - subnet-1a880c14
        - subnet-cc76b5aa
  DeleteFuncionarios:
    handler: handler.deleteFuncionarios
    events:
      - http:
          path: /
          method: delete
          cors: true
    vpc:
      securityGroupIds:
        - sg-ff8bfadd
      subnetIds:
        - subnet-1a29e03b
        - subnet-c4a93b89
        - subnet-7de12e22
        - subnet-48eef876
        - subnet-1a880c14
        - subnet-cc76b5aa
